// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xdrfaqdtdxuqocxzuiee.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhkcmZhcWR0ZHh1cW9jeHp1aWVlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ2NzI5ODcsImV4cCI6MjA2MDI0ODk4N30.7VOO6dY_yj2stiVh2nxGfipffzyEa421uWDzB24qOLw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);